---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terradesk-plugin-cache
  labels:
    {{- include "Devhub.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      {{- include "Devhub.selectorLabels" . | nindent 8 }}