---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devhub
  labels:
    {{- include "Devhub.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts/token"]
  verbs: ["create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devhub
  labels:
    {{- include "Devhub.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: devhub
roleRef:
  kind: Role
  name: devhub
  apiGroup: rbac.authorization.k8s.io