{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "internal-secrets") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: internal-secrets
type: Opaque
data:
  CLOAK_KEY_V1: {{ (get $secretData "CLOAK_KEY_V1") | default (randAlphaNum 32 | b64enc | b64enc) | quote }}
  SECRET_KEY_BASE: {{ (get $secretData "SECRET_KEY_BASE") | default (randAlphaNum 64 | b64enc) | quote }}
  {{- if .Values.postgresql.enabled }}
  DB_HOSTNAME: {{ (printf "%s-postgresql" (include "Devhub.fullname" .)) | b64enc | quote }}
  DB_PASSWORD: {{ include "Devhub.defaultDatabasePassword" . | quote }}
  {{- end }}
  DB_NAME: {{ "devhub" | b64enc | quote }}
  DB_USERNAME: {{ "postgres" | b64enc | quote }}
  DB_PORT: {{ "5432" | b64enc | quote }}