apiVersion: v1
kind: Service
metadata:
  name: {{ include "DevHub.fullname" . }}
  labels: {{- include "DevHub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 5432
      targetPort: postgres-proxy
      protocol: TCP
      name: postgres-proxy
  selector: {{- include "DevHub.selectorLabels" . | nindent 4 }}