{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "devhub-config") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: devhub-config
type: Opaque
data:
  CLOAK_KEY_V1: {{ (get $secretData "CLOAK_KEY_V1") | default (randAlphaNum 32 | b64enc | b64enc) | quote }}
  SECRET_KEY_BASE: {{ (get $secretData "SECRET_KEY_BASE") | default (randAlphaNum 64 | b64enc) | quote }}
  {{- if .Values.postgresql.enabled }}
  DB_HOSTNAME: {{ (printf "%s-postgresql" (include "DevHub.name" .)) | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
  DB_PASSWORD: {{ include "DevHub.defaultDatabasePassword" . | quote }}
  DB_SSL: {{ "false" | b64enc | quote }}
  {{- end }}